name: daily scrape

on:
  schedule:
    - cron: "10 0 * * *"   # 毎日 09:10 JST（=00:10 UTC）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily script
        run: |
          python run_daily.py

      - name: Commit updated Excel
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/funaduri_daily.xlsx || true
          git commit -m "daily update" || echo "no changes"
          git push
